png++: png::image< pixel >::pixel_consumer Class Reference
png::image< pixel >::pixel_consumer Class Reference
The pixel buffer adapter for reading pixel data.
#include <image.hpp>
Public Member Functions
pixel_consumer (image_info &info, pixbuf &pixels)
void reset (size_t pass)
Public Member Functions inherited from png::image< pixel >::streaming_impl< consumer< pixel, pixel_consumer, image_info_ref_holder, true > >
streaming_impl (image_info &info, pixbuf &pixels)
byte * get_next_row (size_t pos)
Returns the starting address of a pos-th row in the image's pixel buffer.
Public Member Functions inherited from png::consumer< pixel, pixel_consumer, image_info_ref_holder, true >
void read (istream &stream)
Reads an image from the stream using default io transformation.
void read (istream &stream, transformation const &transform)
Reads an image from the stream using custom io transformation.
Public Member Functions inherited from png::streaming_base< pixel, image_info_ref_holder >
streaming_base (image_info &info)
streaming_base (size_t width, size_t height)
image_info const & get_info () const
Additional Inherited Members
Public Types inherited from png::consumer< pixel, pixel_consumer, image_info_ref_holder, true >
typedef pixel_traits< pixel > traits
Public Types inherited from png::streaming_base< pixel, image_info_ref_holder >
typedef pixel_traits< pixel > traits
Protected Types inherited from png::consumer< pixel, pixel_consumer, image_info_ref_holder, true >
typedef streaming_base< pixel,
image_info_ref_holder > base
Protected Member Functions inherited from png::consumer< pixel, pixel_consumer, image_info_ref_holder, true >
consumer (image_info &info)
Constructs a consumer object using passed image_info object to store image information.
Protected Member Functions inherited from png::streaming_base< pixel, image_info_ref_holder >
image_info & get_info ()
void reset (size_t)
Protected Attributes inherited from png::image< pixel >::streaming_impl< consumer< pixel, pixel_consumer, image_info_ref_holder, true > >
pixbuf & m_pixbuf
Protected Attributes inherited from png::streaming_base< pixel, image_info_ref_holder >
image_info_ref_holder m_info_holder
Detailed Description
template<typename pixel>
class png::image< pixel >::pixel_consumer
The pixel buffer adapter for reading pixel data.
Constructor & Destructor Documentation
template<typename pixel > png::image< pixel >::pixel_consumer::pixel_consumer (image_info & info, pixbuf & pixels) inline
Member Function Documentation
template<typename pixel > void png::image< pixel >::pixel_consumer::reset (size_t pass) inline
References png::image< pixel >::get_height(), png::streaming_base< pixel, image_info_ref_holder >::get_info(), png::image< pixel >::get_width(), png::image< pixel >::streaming_impl< consumer< pixel, pixel_consumer, image_info_ref_holder, true > >::m_pixbuf, and png::basic_pixel_buffer< pixel, row, traits >::resize().
The documentation for this class was generated from the following file:
image.hpp